package vn.alpaca.alpacajavatraininglast2021.object.constant;

public enum Authorities {

    USER_READ("USER_READ"),
    USER_CREATE("USER_CREATE"),
    USER_UPDATE("USER_UPDATE"),
    USER_DELETE("USER_DELETE"),
    SYSTEM_ROLE_READ("SYSTEM_ROLE_READ"),
    SYSTEM_ROLE_CREATE("SYSTEM_ROLE_CREATE"),
    SYSTEM_ROLE_UPDATE("SYSTEM_ROLE_UPDATE"),
    SYSTEM_ROLE_DELETE("SYSTEM_ROLE_DELETE"),
    AUTHORITY_READ("AUTHORITY_READ"),
    AUTHORITY_CREATE("AUTHORITY_CREATE"),
    AUTHORITY_UPDATE("AUTHORITY_UPDATE"),
    AUTHORITY_DELETE("AUTHORITY_DELETE"),
    CUSTOMER_READ("CUSTOMER_READ"),
    CUSTOMER_CREATE("CUSTOMER_CREATE"),
    CUSTOMER_UPDATE("CUSTOMER_UPDATE"),
    CUSTOMER_DELETE("CUSTOMER_DELETE"),
    CLAIM_REQUEST_READ("CLAIM_REQUEST_READ"),
    CLAIM_REQUEST_CREATE("CLAIM_REQUEST_CREATE"),
    CLAIM_REQUEST_UPDATE("CLAIM_REQUEST_UPDATE"),
    CLAIM_REQUEST_DELETE("CLAIM_REQUEST_DELETE"),
    ANALYZED_RECEIPT_READ("ANALYZED_RECEIPT_READ"),
    ANALYZED_RECEIPT_CREATE("ANALYZED_RECEIPT_CREATE"),
    ANALYZED_RECEIPT_UPDATE("ANALYZED_RECEIPT_UPDATE"),
    ANALYZED_RECEIPT_DELETE("ANALYZED_RECEIPT_DELETE"),
    CONTRACT_READ("CONTRACT_READ"),
    CONTRACT_CREATE("CONTRACT_CREATE"),
    CONTRACT_UPDATE("CONTRACT_UPDATE"),
    CONTRACT_DELETE("CONTRACT_DELETE"),
    PAYMENT_READ("PAYMENT_READ"),
    PAYMENT_CREATE("PAYMENT_CREATE"),
    PAYMENT_UPDATE("PAYMENT_UPDATE"),
    PAYMENT_DELETE("PAYMENT_DELETE");

    public final String permission;

    Authorities(String permission) {this.permission = permission;}

    public String getPermission() {
        return permission;
    }
}
