eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8300
spring:
  application:
    name: send-claim-request-service
  datasource:
    url: jdbc:postgresql://localhost:5432/alpaca_pj_01
    username: alpaca
    password: alpaca@@@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        minimumNumberOfCalls: 100
        failureRateThreshold: 60
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        allowHealthIndicatorToFail: true
    instances:
      sendRequest:
        baseConfig: default
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 5
  ratelimiter:
    instances:
      sendRequest:
        limitForPeriod: 1
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
  retry:
    instances:
      sendRequest:
        maxRetryAttemps: 2
        waitDuration: 1s
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 25
        maxWaitDuration: 0
        writableStackTraceEnabled: true
        fairCallHandlingEnabled: true
    instances:
      sendRequest:
        baseConfig: default
        maxConcurrentCalls: 2
        maxWaitDuration: 2s