eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8300
spring:
  application:
    name: send-claim-request-service
  datasource:
    url: jdbc:postgresql://localhost:5432/alpaca_pj_01
    username: alpaca
    password: alpaca@@@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always