eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8762
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: send-claim-request-service
          uri: lb://send-claim-request-service/
          predicates:
            - Path=/send-claim-request/**
          filters:
            - StripPrefix=1
        - id: handle-claim-request-service
          uri: lb://handle-claim-request-service/
          predicates:
            - Path=/handle-claim-request/**
          filters:
            - StripPrefix=1
        - id: customer-service
          uri: lb://customer-service/
          predicates:
            - Path=/customers/**
          filters:
            - StripPrefix=1
        - id: contract-service
          uri: lb://contract-service/
          predicates:
            - Path=/contracts/**
          filters:
            - StripPrefix=1

  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration