eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8762
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authentication-service
          uri: lb://authentication-service/
          predicates:
              - Path=/auth/**
          filters:
              - StripPrefix=1
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: send-claim-request-service
          uri: lb://send-claim-request-service/
          predicates:
            - Path=/send-claim-request/**
          filters:
            - StripPrefix=1
        - id: handle-claim-request-service
          uri: lb://handle-claim-request-service/
          predicates:
            - Path=/handle-claim-request/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: customer-service
          uri: lb://customer-service/
          predicates:
            - Path=/customers/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: contract-service
          uri: lb://contract-service/
          predicates:
            - Path=/contracts/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

  main:
    web-application-type: reactive
  sleuth:
    reactor:
      instrumentation-type: decorate_on_each
  zipkin:
    base-url: http://localhost:9411
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration