eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 9090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-server
          uri: lb://auth-server/
          predicates:
              - Path=/auth-server/**
          filters:
              - StripPrefix=1
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: send-claim-request-service
          uri: lb://send-claim-request-service/
          predicates:
            - Path=/send-claim-request-service/**
          filters:
            - StripPrefix=1
        - id: handle-claim-request-service
          uri: lb://handle-claim-request-service/
          predicates:
            - Path=/send-claim-request-service/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
              args:
                ignoredPaths:
                  - /payments/customer/**
                  - /claim-requests/customer/**
        - id: customer-service
          uri: lb://customer-service/
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
              args:
                ignoredPaths:
                  - /search/id-card/**
        - id: contract-service
          uri: lb://contract-service/
          predicates:
            - Path=/contract-service/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
              args:
                ignoredPaths:
                  - /search/customer-id-card/**

  main:
    web-application-type: reactive
  sleuth:
    reactor:
      instrumentation-type: decorate_on_each
  zipkin:
    base-url: http://localhost:9411
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration