eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8762
spring:
  application:
    name: gateway-server
zuul:
  ignored-services: '*'
  routes:
    assets-service:
      path: '/assets/**'
      service-id: 'assets-service'
  sensitive-headers: 'Authorization'
