eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8762
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: assets-service
          uri: lb://assets-service/
          predicates:
            - Path=/assets/**
          filters:
            - StripPrefix=1
  main:
    web-application-type: reactive