eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8762
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: crud-service
          uri: lb://crud-service/
          predicates:
            - Path=/crud/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: send-claim-request-service
          uri: lb://send-claim-request-service/
          predicates:
            - Path=/claim-request/**
          filters:
            - StripPrefix=1
  main:
    web-application-type: reactive