eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8765
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/alpaca_pj_01
    username: alpaca
    password: alpaca@@@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
feign:
  autoconfiguration:
    jackson:
      enabled: true
alpaca:
  security:
    jwt:
      secret: alpaca@@@alpaca@@@alpaca@@@alpaca@@@
      expiration: 84000000
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG
debug: true