eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8600
spring:
  application:
    name: authentication-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
feign:
  autoconfiguration:
    jackson:
      enabled: true
alpaca:
  security:
    jwt:
      secret: alpaca@@@alpaca@@@alpaca@@@alpaca@@@
      expiration: 84000000