eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8400
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/alpaca_pj_01
    username: alpaca
    password: alpaca@@@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update



