eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8200
spring:
  application:
    name: handle-claim-request-service
  datasource:
    url: jdbc:postgresql://localhost:5432/alpaca_pj_01
    username: alpaca
    password: alpaca@@@